set(_LINK_EXE_LLD_RULE "ld.lld --entry start <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET>")

set(CMAKE_C_LINK_EXECUTABLE ${_LINK_EXE_LLD_RULE})
set(CMAKE_CXX_LINK_EXECUTABLE ${_LINK_EXE_LLD_RULE})