set(LLD_ARM_LINKER_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/link-arm.ld)
set(_LINK_EXE_LLD_RULE "ld.lld --script ${CMAKE_CURRENT_LIST_DIR}/link-arm.ld --entry start <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET>")

set(CMAKE_C_LINK_EXECUTABLE ${_LINK_EXE_LLD_RULE})
set(CMAKE_CXX_LINK_EXECUTABLE ${_LINK_EXE_LLD_RULE})